### ISSUE TITLE
Cuts at hole

### ISSUE THREAD

**Issue by rajithpadmanabhan** [rogerdahl/ws2812b-neopixel-stuff#1]
Is there a setting that can force the cuts to be at a hole? 
This makes it easier for me to gouge out the track with a twist drill instead of using a box cutter.

**Comment by rogerdahl** [comment]
Sounds like this is a question re. StripRouter? This is a different project. If StripRouter, then sorry, there's no such setting, but it's on my list of things I'd like to implement.

**Comment by rajithpadmanabhan** [comment]
So sorry to post in the wrong place. I'm  not much of a git user.
The drill actually helps a lot since one can visually confirm the break
quite easily. I'll keep an eye on the project.
